import { DesignSystem, DesignSystemSlug } from "./types";

export const designSystems: Record<DesignSystemSlug, DesignSystem> = {
  ooh: {
    name: "OOH Advertising",
    description: "Digital Billboards & DOOH",
    icon: "○",
    fontHeading: "Inter",
    fontBody: "Inter",
    fontMono: "JetBrains Mono",
    rationale: "Blue-forward palette for DOOH advertising platforms. Energy Blue (#1E76BB) primary with flowing teal accents creates a movement-first visual language for digital out-of-home advertising. Dark navy backgrounds ensure high legibility on outdoor displays.",
    colors: {
      primary: "from-blue-600 to-blue-500",
      primaryHex: "#1E76BB",
      secondary: "from-indigo-700 to-indigo-600",
      secondaryHex: "#2A3B8F",
      accent: "from-sky-400 to-cyan-400",
      accentHex: "#61CBF5",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      info: "#61CBF5",
      background: "#05080F",
      surface: "#0C1425",
      surfaceHover: "#172242",
      border: "#1E2D4A",
      text: "#FAFAFA",
      textMuted: "#94A3B8",
      overlay: "#00000080",
    },
  },
  "data-science": {
    name: "Data Science",
    description: "Analytics & Visualization",
    icon: "◇",
    fontHeading: "Inter",
    fontBody: "Inter",
    fontMono: "JetBrains Mono",
    rationale: "Cold-toned palette designed for dense data dashboards. Teal and blue create a calm analytical environment where data stands out. High info-density support with muted backgrounds.",
    colors: {
      primary: "from-teal-400 to-cyan-500",
      primaryHex: "#14B8A6",
      secondary: "from-blue-400 to-indigo-500",
      secondaryHex: "#3B82F6",
      accent: "from-emerald-400 to-green-500",
      accentHex: "#10B981",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      info: "#3B82F6",
      background: "#030712",
      surface: "#0F172A",
      surfaceHover: "#1E293B",
      border: "#1E293B",
      text: "#F8FAFC",
      textMuted: "#94A3B8",
      overlay: "#00000080",
    },
  },
  ai: {
    name: "AI Applications",
    description: "LLMs & Agent Interfaces",
    icon: "◇",
    fontHeading: "Inter",
    fontBody: "Inter",
    fontMono: "JetBrains Mono",
    rationale: "Futuristic palette with deep purple foundations and electric accents. Designed for chat interfaces, agent UIs, and model outputs. Glass-morphic elements with cyan glow effects.",
    colors: {
      primary: "from-fuchsia-500 to-violet-600",
      primaryHex: "#D946EF",
      secondary: "from-cyan-400 to-teal-500",
      secondaryHex: "#06B6D4",
      accent: "from-violet-400 to-purple-500",
      accentHex: "#8B5CF6",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      info: "#8B5CF6",
      background: "#0A0515",
      surface: "#140B2E",
      surfaceHover: "#1E1040",
      border: "#2D1B69",
      text: "#F5F3FF",
      textMuted: "#A78BFA",
      overlay: "#00000080",
    },
  },
  "design-engineering": {
    name: "Design Engineering",
    description: "Dev Tools & Libraries",
    icon: "◇",
    fontHeading: "Inter",
    fontBody: "Inter",
    fontMono: "JetBrains Mono",
    rationale: "Warm slate palette for developer tooling and component libraries. Amber accents provide clear visual hierarchy. Practical, minimal, and readable at small sizes.",
    colors: {
      primary: "from-amber-400 to-orange-500",
      primaryHex: "#F59E0B",
      secondary: "from-green-400 to-emerald-500",
      secondaryHex: "#22C55E",
      accent: "from-orange-400 to-red-500",
      accentHex: "#F97316",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      info: "#3B82F6",
      background: "#0C0A09",
      surface: "#1C1917",
      surfaceHover: "#292524",
      border: "#292524",
      text: "#FAFAF9",
      textMuted: "#A8A29E",
      overlay: "#00000080",
    },
  },
  fintech: {
    name: "FinTech",
    description: "Banking & Payments",
    icon: "◇",
    fontHeading: "Inter",
    fontBody: "Inter",
    fontMono: "JetBrains Mono",
    rationale: "Conservative palette inspired by institutional finance. Navy foundations communicate trust. Emerald signals growth. Gold accents for premium feel. Sharp corners and restrained spacing.",
    colors: {
      primary: "from-blue-500 to-indigo-600",
      primaryHex: "#3B82F6",
      secondary: "from-emerald-400 to-teal-500",
      secondaryHex: "#10B981",
      accent: "from-amber-400 to-yellow-500",
      accentHex: "#F59E0B",
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
      info: "#3B82F6",
      background: "#020617",
      surface: "#0F172A",
      surfaceHover: "#1E293B",
      border: "#1E293B",
      text: "#F8FAFC",
      textMuted: "#94A3B8",
      overlay: "#00000080",
    },
  },
  consumer: {
    name: "Consumer",
    description: "E-commerce & Social",
    icon: "◇",
    fontHeading: "Inter",
    fontBody: "Inter",
    fontMono: "JetBrains Mono",
    rationale: "Vibrant, playful palette for consumer-facing applications. Rose and amber create emotional warmth. Rounded corners and generous spacing signal approachability.",
    colors: {
      primary: "from-rose-500 to-pink-600",
      primaryHex: "#F43F5E",
      secondary: "from-amber-400 to-orange-500",
      secondaryHex: "#FB923C",
      accent: "from-violet-400 to-purple-500",
      accentHex: "#A78BFA",
      success: "#4ADE80",
      warning: "#FBBF24",
      error: "#F87171",
      info: "#60A5FA",
      background: "#0C0A09",
      surface: "#1C1917",
      surfaceHover: "#292524",
      border: "#44403C",
      text: "#FAFAF9",
      textMuted: "#D6D3D1",
      overlay: "#00000080",
    },
  },
};

export const designSystemList = Object.entries(designSystems).map(([slug, ds]) => ({
  slug: slug as DesignSystemSlug,
  ...ds,
}));
